name: Digraphs
version: 0.5
date: 03/03/2016
description: 

authors:
    - name: J. De Beule
      url: http://homepages.vub.ac.be/~jdbeule/
    - name: J. Jonusas
      url: http://www-circa.mcs.st-and.ac.uk/~julius
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6
    - name: M. Torpey
      url: http://www-circa.mcs.st-and.ac.uk/~mct25
    - name: W. Wilson
      url: http://www-circa.mcs.st-and.ac.uk/~waw7

maintainers:
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6

GAP: ">=4.8.2"

needed-pkgs:
    - name: "io"
      version: ">=4.4.4"
      url: "http://gap-packages.github.io/io/"
    - name: "orb"
      version: ">=4.7.5"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.5"
      url: "http://www.maths.qmul.ac.uk/~leonard/grape/"

www: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/digraphs.php
readme: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/digraphs/README.md
packageinfo: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/digraphs/digraphs-0.5.tar.gz

abstract: The <b>Digraphs</b> package is a <b>GAP</b> package containing methods for digraphs and multidigraphs.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
